import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.awt.image.BufferedImageOp;
import java.awt.image.ConvolveOp;
import java.awt.image.Kernel;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.data.category.DefaultCategoryDataset;


public class FormPCD extends javax.swing.JFrame {
    
    String sumberGambar;
    Image image;
    Dimension size;
    BufferedImage prosesimage;
    BufferedImage prosesimage2;
    BufferedImage prosesimage3;
    
    int histogram[] = new int[256];
    int kumulatif[] = new int[256];
    
    public FormPCD() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblGambar1 = new javax.swing.JLabel();
        lblGambar2 = new javax.swing.JLabel();
        jSlider1 = new javax.swing.JSlider();
        jSlider2 = new javax.swing.JSlider();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblGambar3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        File = new javax.swing.JMenu();
        mnuOpen = new javax.swing.JMenuItem();
        mnuOpen2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        Deteksitepi = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        Noise = new javax.swing.JMenu();
        noiseuniform = new javax.swing.JMenuItem();
        noisesalt = new javax.swing.JMenuItem();
        noisespeckel = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblGambar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblGambar1.setName("lblGambar1"); // NOI18N

        lblGambar2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jSlider1.setMaximum(255);
        jSlider1.setMinimum(-255);
        jSlider1.setValue(0);

        jSlider2.setMinimum(-100);
        jSlider2.setValue(0);

        jLabel3.setText("Nilai Thresholding:");

        jLabel4.setText("C");

        jLabel5.setText("Y");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jButton1.setText("RGB To Grayscale");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Binary");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Invers");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Invers Log");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Trans Power");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Brightness");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Contrast");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Thresholding");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("Histogram Equalization");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("Histogram");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jLabel1.setText("Brightness");

        jLabel2.setText("Contrast");

        jLabel6.setText("NOISE");

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jLabel7.setText("P (Noise)");

        jLabel8.setText("SNR Awal");

        jLabel9.setText("SNR Akhir");

        lblGambar3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel10.setText("Hasil reduksi noise");

        File.setText("File");

        mnuOpen.setText("open");
        mnuOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuOpenActionPerformed(evt);
            }
        });
        File.add(mnuOpen);

        mnuOpen2.setText("open2");
        mnuOpen2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuOpen2ActionPerformed(evt);
            }
        });
        File.add(mnuOpen2);

        jMenuBar1.add(File);

        jMenu3.setText("LPF");

        jMenuItem1.setText("3x3 rata2");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuItem2.setText("3x3 Koef.");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuItem3.setText("3x3 Koef2");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuBar1.add(jMenu3);

        jMenu1.setText("HPF");

        jMenuItem4.setText("HPF 1");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem5.setText("HPF 2");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuBar1.add(jMenu1);

        Deteksitepi.setText("Deteksi Tepi");

        jMenuItem7.setText("Prewitte");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        Deteksitepi.add(jMenuItem7);

        jMenuItem8.setText("Gausian 5x5");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        Deteksitepi.add(jMenuItem8);

        jMenuItem9.setText("Sobel1 3x3");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        Deteksitepi.add(jMenuItem9);

        jMenuItem10.setText("Prewitte 2");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        Deteksitepi.add(jMenuItem10);

        jMenuItem11.setText("Sobel2 3x3");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        Deteksitepi.add(jMenuItem11);

        jMenuItem12.setText("Sobel3 3x3");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        Deteksitepi.add(jMenuItem12);

        jMenuItem13.setText("Laplacian");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        Deteksitepi.add(jMenuItem13);

        jMenuItem14.setText("Robet");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        Deteksitepi.add(jMenuItem14);

        jMenuBar1.add(Deteksitepi);

        Noise.setText("Noise");

        noiseuniform.setText("Noise Uniform");
        noiseuniform.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noiseuniformActionPerformed(evt);
            }
        });
        Noise.add(noiseuniform);

        noisesalt.setText("Noise Salt & pepper");
        noisesalt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noisesaltActionPerformed(evt);
            }
        });
        Noise.add(noisesalt);

        noisespeckel.setText("Noise Speckel");
        noisespeckel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noisespeckelActionPerformed(evt);
            }
        });
        Noise.add(noisespeckel);

        jMenuBar1.add(Noise);

        jMenu2.setText("Reduksi  Noise");

        jMenuItem6.setText("Fitur rata-rata");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(62, 62, 62)))
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField1)
                                    .addComponent(jTextField2)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                                    .addComponent(jTextField4)
                                    .addComponent(jTextField5)
                                    .addComponent(jTextField6)))
                            .addComponent(jLabel8)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jSlider2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblGambar1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(49, 49, 49)
                                        .addComponent(lblGambar2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(52, 52, 52)
                                .addComponent(lblGambar3, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(131, 131, 131)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27))
            .addGroup(layout.createSequentialGroup()
                .addGap(201, 201, 201)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(231, 231, 231))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblGambar1, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                            .addComponent(lblGambar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblGambar3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jSlider2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton9)
                        .addGap(18, 18, 18)
                        .addComponent(jButton10)))
                .addGap(38, 38, 38)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     image = new ImageIcon(sumberGambar).getImage();

    size = new Dimension();

    size.width = image.getWidth(null);
    size.height = image.getHeight(null);

    prosesimage = new BufferedImage(
            size.width,
            size.height,
            BufferedImage.TYPE_INT_RGB);

    Graphics g = prosesimage.getGraphics();

    g.drawImage(image, 0, 0, null);

    for (int x = 0; x < size.width; x++) {
        for (int y = 0; y < size.height; y++) {

            int RGB = prosesimage.getRGB(x, y);

            int alpha = (RGB << 24) & 0xFF;
            int red   = (RGB >> 16) & 0xFF;
            int green = (RGB >> 8) & 0xFF;
            int blue  = (RGB >> 0) & 0xFF;

            int avg = (red + green + blue) / 3;

            int gray = alpha | avg << 16 | avg << 8 | avg;

            prosesimage.setRGB(x, y, gray);
        }
    }

    lblGambar2.setIcon(new ImageIcon(prosesimage));        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    image = new ImageIcon(sumberGambar).getImage();

size = new Dimension();

size.width = image.getWidth(null);
size.height = image.getHeight(null);

prosesimage = new BufferedImage(
        size.width,
        size.height,
        BufferedImage.TYPE_INT_RGB);

Graphics g = prosesimage.getGraphics();

g.drawImage(image, 0, 0, null);

for (int x = 0; x < size.width; x++) {
    for (int y = 0; y < size.height; y++) {

        int RGB = prosesimage.getRGB(x, y);

        int red = (RGB >> 16) & 0xFF;
        int green = (RGB >> 8) & 0xFF;
        int blue = RGB & 0xFF;

        int avg = (red + green + blue) / 3;

        int binary;

        if (avg < 128) {
            binary = 0;
        } else {
            binary = 255;
        }

        int hasil = (binary << 16) | (binary << 8) | binary;

        prosesimage.setRGB(x, y, hasil);
    }
}

lblGambar2.setIcon(new ImageIcon(prosesimage));        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    image = new ImageIcon(sumberGambar).getImage();

    size = new Dimension();

    size.width = image.getWidth(null);
    size.height = image.getHeight(null);

    prosesimage = new BufferedImage(
            size.width,
            size.height,
            BufferedImage.TYPE_INT_RGB);

    Graphics g = prosesimage.getGraphics();

    g.drawImage(image, 0, 0, null);

    for (int x = 0; x < size.width; x++) {
        for (int y = 0; y < size.height; y++) {

            int RGB = prosesimage.getRGB(x, y);

            int red = (RGB >> 16) & 0xFF;
            int green = (RGB >> 8) & 0xFF;
            int blue = RGB & 0xFF;

            int gray = (red + green + blue) / 3;

            int inv = (int)(255 * Math.log(256 - gray) / Math.log(256));

            int hasil =
                    (inv << 16) |
                    (inv << 8) |
                    inv;

            prosesimage.setRGB(x, y, hasil);
        }
    }

    lblGambar2.setIcon(new ImageIcon(prosesimage));    // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
            image = new ImageIcon(sumberGambar).getImage();

    size = new Dimension();

    size.width = image.getWidth(null);
    size.height = image.getHeight(null);

    prosesimage = new BufferedImage(
            size.width,
            size.height,
            BufferedImage.TYPE_INT_RGB);

    Graphics g = prosesimage.getGraphics();

    g.drawImage(image, 0, 0, null);

    int cerah = jSlider1.getValue();

    for(int x=0; x<size.width; x++)
    {
        for(int y=0; y<size.height; y++)
        {
            int rgb = prosesimage.getRGB(x, y);

            int red = (rgb >> 16) & 0xff;
            int green = (rgb >> 8) & 0xff;
            int blue = rgb & 0xff;

            red += cerah;
            green += cerah;
            blue += cerah;

            if(red > 255) red = 255;
            if(green > 255) green = 255;
            if(blue > 255) blue = 255;

            if(red < 0) red = 0;
            if(green < 0) green = 0;
            if(blue < 0) blue = 0;

            int hasil =
                    (red << 16) |
                    (green << 8) |
                    blue;

            prosesimage.setRGB(x, y, hasil);
        }
    }

    lblGambar2.setIcon(new ImageIcon(prosesimage));        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void mnuOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuOpenActionPerformed
        JFileChooser fc = new JFileChooser();

        int open = fc.showOpenDialog(this);

        if(open == JFileChooser.APPROVE_OPTION)
        {
            sumberGambar = fc.getSelectedFile().getPath();

            lblGambar1.setIcon(new ImageIcon(sumberGambar));
        }            // TODO add your handling code here:
    }//GEN-LAST:event_mnuOpenActionPerformed

    private void mnuOpen2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuOpen2ActionPerformed
        JFileChooser fc = new JFileChooser();

        int open = fc.showOpenDialog(this);

        if(open == JFileChooser.APPROVE_OPTION)
        {
            sumberGambar = fc.getSelectedFile().getPath();

            FormGambar fg = new FormGambar();

            fg.tampilkanGambar(sumberGambar);

            fg.setVisible(true);
        }
    }//GEN-LAST:event_mnuOpen2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    image = new ImageIcon(sumberGambar).getImage();

    size = new Dimension();

    size.width = image.getWidth(null);
    size.height = image.getHeight(null);

    prosesimage = new BufferedImage(
            size.width,
            size.height,
            BufferedImage.TYPE_INT_RGB);

    Graphics g = prosesimage.getGraphics();

    g.drawImage(image, 0, 0, null);

    for (int x = 0; x < size.width; x++) {
        for (int y = 0; y < size.height; y++) {

            int RGB = prosesimage.getRGB(x, y);

            int red = (RGB >> 16) & 0xFF;
            int green = (RGB >> 8) & 0xFF;
            int blue = RGB & 0xFF;

            int invRed = 255 - red;
            int invGreen = 255 - green;
            int invBlue = 255 - blue;

            int invers =
                    (invRed << 16) |
                    (invGreen << 8) |
                    invBlue;

            prosesimage.setRGB(x, y, invers);
        }
    }

    lblGambar2.setIcon(new ImageIcon(prosesimage));        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
     image = new ImageIcon(sumberGambar).getImage();

    size = new Dimension();

    size.width = image.getWidth(null);
    size.height = image.getHeight(null);

    int th = Integer.parseInt(jTextField1.getText());

    prosesimage = new BufferedImage(
            size.width,
            size.height,
            BufferedImage.TYPE_INT_RGB);

    Graphics g = prosesimage.getGraphics();

    g.drawImage(image, 0, 0, null);

    for (int x = 0; x < size.width; x++) {
        for (int y = 0; y < size.height; y++) {

            int RGB = prosesimage.getRGB(x, y);

            int red = (RGB >> 16) & 0xFF;
            int green = (RGB >> 8) & 0xFF;
            int blue = RGB & 0xFF;

            int avg = (red + green + blue) / 3;

            int hasil;

            if (avg < th) {
                hasil = 0;
            } else {
                hasil = 255;
            }

            int gray =
                    (hasil << 16) |
                    (hasil << 8) |
                    hasil;

            prosesimage.setRGB(x, y, gray);
        }
    }

    lblGambar2.setIcon(new ImageIcon(prosesimage));    // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
         image = new ImageIcon(sumberGambar).getImage();

    size = new Dimension();

    size.width = image.getWidth(null);
    size.height = image.getHeight(null);

    prosesimage = new BufferedImage(
            size.width,
            size.height,
            BufferedImage.TYPE_INT_RGB);

    Graphics g = prosesimage.getGraphics();

    g.drawImage(image, 0, 0, null);

    drawHistogram(prosesimage, "Histogram Citra");
}

void drawHistogram(BufferedImage test, String judul)
{
    int width = test.getWidth();
    int height = test.getHeight();

    int count[][] = new int[4][256];

    for(int i=0;i<width;i++)
    {
        for(int j=0;j<height;j++)
        {
            int color = test.getRGB(i,j);

            int red = (color & 0x00ff0000)>>16;
            int green = (color & 0x0000ff00)>>8;
            int blue = color & 0x000000ff;

            int gray = (red + green + blue)/3;

            count[0][red]++;
            count[1][green]++;
            count[2][blue]++;
            count[3][gray]++;
        }
    }

    DefaultCategoryDataset dataset =
            new DefaultCategoryDataset();

    for(int i=0;i<256;i++)
    {
        dataset.addValue(count[0][i], "Red", String.valueOf(i));
        dataset.addValue(count[1][i], "Green", String.valueOf(i));
        dataset.addValue(count[2][i], "Blue", String.valueOf(i));
        dataset.addValue(count[3][i], "Gray", String.valueOf(i));
    }

    JFreeChart chart =
            ChartFactory.createBarChart(
                    "Histogram",
                    "Pixel",
                    "Frekuensi",
                    dataset);

    ChartFrame frame =
            new ChartFrame(judul, chart);

    frame.setSize(800,500);
    frame.setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
           image = new ImageIcon(sumberGambar).getImage();

    size = new Dimension();

    size.width = image.getWidth(null);
    size.height = image.getHeight(null);

    prosesimage = new BufferedImage(
            size.width,
            size.height,
            BufferedImage.TYPE_INT_RGB);

    Graphics g = prosesimage.getGraphics();

    g.drawImage(image, 0, 0, null);

    int kontras = jSlider2.getValue();

    for(int x = 0; x < size.width; x++)
    {
        for(int y = 0; y < size.height; y++)
        {
            int rgb = prosesimage.getRGB(x, y);

            int red = (rgb >> 16) & 0xff;
            int green = (rgb >> 8) & 0xff;
            int blue = rgb & 0xff;

            if(red > 128)
                red += kontras;
            else
                red -= kontras;

            if(green > 128)
                green += kontras;
            else
                green -= kontras;

            if(blue > 128)
                blue += kontras;
            else
                blue -= kontras;

            if(red > 255) red = 255;
            if(green > 255) green = 255;
            if(blue > 255) blue = 255;

            if(red < 0) red = 0;
            if(green < 0) green = 0;
            if(blue < 0) blue = 0;

            int hasil =
                    (red << 16) |
                    (green << 8) |
                    blue;

            prosesimage.setRGB(x, y, hasil);
        }
    }

    lblGambar2.setIcon(new ImageIcon(prosesimage));
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
            image = new ImageIcon(sumberGambar).getImage();

    size = new Dimension();

    size.width = image.getWidth(null);
    size.height = image.getHeight(null);

    prosesimage = new BufferedImage(
            size.width,
            size.height,
            BufferedImage.TYPE_INT_RGB);

    Graphics g = prosesimage.getGraphics();

    g.drawImage(image, 0, 0, null);

    for(int i = 0; i < 256; i++)
    {
        histogram[i] = 0;
    }

    for(int x = 0; x < size.width; x++)
    {
        for(int y = 0; y < size.height; y++)
        {
            int rgb = prosesimage.getRGB(x, y);

            int red = (rgb >> 16) & 0xff;
            int green = (rgb >> 8) & 0xff;
            int blue = rgb & 0xff;

            int gray = (red + green + blue) / 3;

            histogram[gray]++;
        }
    }

    kumulatif[0] = histogram[0];

    for(int i = 1; i < 256; i++)
    {
        kumulatif[i] = kumulatif[i - 1] + histogram[i];
    }

    int totalPixel = size.width * size.height;

    for(int x = 0; x < size.width; x++)
    {
        for(int y = 0; y < size.height; y++)
        {
            int rgb = prosesimage.getRGB(x, y);

            int red = (rgb >> 16) & 0xff;
            int green = (rgb >> 8) & 0xff;
            int blue = rgb & 0xff;

            int gray = (red + green + blue) / 3;

            int eq =
                (kumulatif[gray] * 255)
                / totalPixel;

            int hasil =
                    (eq << 16) |
                    (eq << 8) |
                    eq;

            prosesimage.setRGB(x, y, hasil);
        }
    }

    lblGambar2.setIcon(new ImageIcon(prosesimage));
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        image = new ImageIcon(sumberGambar).getImage();

        size = new Dimension();
        size.width = image.getWidth(null);
        size.height = image.getHeight(null);
        setPreferredSize(size);

        prosesimage3 = new BufferedImage(size.width, size.height, BufferedImage.TYPE_INT_RGB);
        prosesimage = new BufferedImage(size.width, size.height, BufferedImage.TYPE_INT_RGB);

        Graphics g = prosesimage.getGraphics();
        g.drawImage(image, 0, 0, null);

        for (int x = 0; x < size.width; x++) {
            for (int y = 0; y < size.height; y++) {

                int RGB = prosesimage.getRGB(x, y);

                int alpha = (RGB << 24) & 0xFF;
                int red = (RGB >> 16) & 0xFF;
                int green = (RGB >> 8) & 0xFF;
                int blue = (RGB >> 0) & 0xFF;

                int avg = (red + green + blue) / 3;
                int gray = alpha | avg << 16 | avg << 8 | avg;

                prosesimage.setRGB(x, y, gray);
            }
        }

        for (int v = 1; v <= size.height - 2; v++) {
            for (int u = 1; u <= size.width - 2; u++) {

                int sum = 0;
                int temp = 0;

                for (int j = -1; j <= 1; j++) {
                    for (int i = -1; i <= 1; i++) {

                        int RGB = prosesimage.getRGB(u + i, v + j);

                        int alpha = (RGB << 24) & 0xFF;
                        int red = (RGB >> 16) & 0xFF;

                        temp = alpha;
                        sum = sum + red;
                    }
                }

                int q = (int) Math.round(sum / 9.0);
                int gray2 = temp | q << 16 | q << 8 | q;

                prosesimage3.setRGB(u, v, gray2);
            }
        }

        lblGambar1.setIcon(new ImageIcon(prosesimage));
        lblGambar2.setIcon(new ImageIcon(prosesimage3));

// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        image = new ImageIcon(sumberGambar).getImage();

        size = new Dimension();
        size.width = image.getWidth(null);
        size.height = image.getHeight(null);
        setPreferredSize(size);

        prosesimage3 = new BufferedImage(size.width, size.height, BufferedImage.TYPE_INT_RGB);
        prosesimage = new BufferedImage(size.width, size.height, BufferedImage.TYPE_INT_RGB);

        Graphics g = prosesimage.getGraphics();
        g.drawImage(image, 0, 0, null);

        double filter[][] = {
            {0.075, 0.125, 0.075},
            {0.125, 0.200, 0.125},
            {0.075, 0.125, 0.075}
        };

        for (int x = 0; x < size.width; x++) {
            for (int y = 0; y < size.height; y++) {

                int RGB = prosesimage.getRGB(x, y);

                int alpha = (RGB << 24) & 0xFF;
                int red = (RGB >> 16) & 0xFF;
                int green = (RGB >> 8) & 0xFF;
                int blue = (RGB >> 0) & 0xFF;

                int avg = (red + green + blue) / 3;
                int gray = alpha | avg << 16 | avg << 8 | avg;

                prosesimage.setRGB(x, y, gray);
            }
        }

        for (int v = 1; v <= size.height - 2; v++) {
            for (int u = 1; u <= size.width - 2; u++) {

                int sum = 0;
                int temp = 0;

                for (int j = -1; j <= 1; j++) {
                    for (int i = -1; i <= 1; i++) {

                        int RGB = prosesimage.getRGB(u + i, v + j);

                        int alpha = (RGB << 24) & 0xFF;
                        int red = (RGB >> 16) & 0xFF;

                        temp = alpha;

                        double c = filter[j + 1][i + 1];
                        sum = (int) (sum + c * red);
                    }
                }

                int q = (int) Math.round(sum);
                int gray2 = temp | q << 16 | q << 8 | q;

                prosesimage3.setRGB(u, v, gray2);
            }
        }

        lblGambar1.setIcon(new ImageIcon(prosesimage));
        lblGambar2.setIcon(new ImageIcon(prosesimage3));// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        image = new ImageIcon(sumberGambar).getImage();

        size = new Dimension();
        size.width = image.getWidth(null);
        size.height = image.getHeight(null);
        setPreferredSize(size);

        prosesimage3 = new BufferedImage(size.width, size.height, BufferedImage.TYPE_INT_RGB);
        prosesimage = new BufferedImage(size.width, size.height, BufferedImage.TYPE_INT_RGB);

        Graphics g = prosesimage.getGraphics();
        g.drawImage(image, 0, 0, null);

        double filter[][] = {
            {1, 1, 1},
            {1, 4, 1},
            {1, 1, 1}
        };

        for (int x = 0; x < size.width; x++) {
            for (int y = 0; y < size.height; y++) {

                int RGB = prosesimage.getRGB(x, y);

                int alpha = (RGB << 24) & 0xFF;
                int red = (RGB >> 16) & 0xFF;
                int green = (RGB >> 8) & 0xFF;
                int blue = (RGB >> 0) & 0xFF;

                int avg = (red + green + blue) / 3;
                int gray = alpha | avg << 16 | avg << 8 | avg;

                prosesimage.setRGB(x, y, gray);
            }
        }

        for (int v = 1; v <= size.height - 2; v++) {
            for (int u = 1; u <= size.width - 2; u++) {

                int sum = 0;
                int temp = 0;

                for (int j = -1; j <= 1; j++) {
                    for (int i = -1; i <= 1; i++) {

                        int RGB = prosesimage.getRGB(u + i, v + j);

                        int alpha = (RGB << 24) & 0xFF;
                        int red = (RGB >> 16) & 0xFF;

                        temp = alpha;

                        double c = filter[j + 1][i + 1];
                        sum = (int) (sum + c * red);
                    }
                }

                int q = (int) Math.round(sum / 12);
                int gray2 = temp | q << 16 | q << 8 | q;

                prosesimage3.setRGB(u, v, gray2);
            }
        }

        lblGambar1.setIcon(new ImageIcon(prosesimage));
        lblGambar2.setIcon(new ImageIcon(prosesimage3));// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        image = new ImageIcon(sumberGambar).getImage();

        size = new Dimension();
        size.width = image.getWidth(null);
        size.height = image.getHeight(null);
        setPreferredSize(size);

        prosesimage3 = new BufferedImage(size.width, size.height, BufferedImage.TYPE_INT_RGB);
        prosesimage = new BufferedImage(size.width, size.height, BufferedImage.TYPE_INT_RGB);

        Graphics g = prosesimage.getGraphics();
        g.drawImage(image, 0, 0, null);

        double filter[][] = {
            {0, -1, 0},
            {-1, 5, -1},
            {0, -1, 0}
        };

        for (int x = 0; x < size.width; x++) {
            for (int y = 0; y < size.height; y++) {

                int RGB = prosesimage.getRGB(x, y);

                int alpha = (RGB << 24) & 0xFF;
                int red = (RGB >> 16) & 0xFF;
                int green = (RGB >> 8) & 0xFF;
                int blue = (RGB >> 0) & 0xFF;

                int avg = (red + green + blue) / 3;
                int gray = alpha | avg << 16 | avg << 8 | avg;

                prosesimage.setRGB(x, y, gray);
            }
        }

        for (int v = 1; v <= size.height - 2; v++) {
            for (int u = 1; u <= size.width - 2; u++) {

                int sum = 0;
                int temp = 0;

                for (int j = -1; j <= 1; j++) {
                    for (int i = -1; i <= 1; i++) {

                        int RGB = prosesimage.getRGB(u + i, v + j);

                        int alpha = (RGB << 24) & 0xFF;
                        int red = (RGB >> 16) & 0xFF;

                        temp = alpha;

                        double c = filter[j + 1][i + 1];
                        sum = (int) (sum + c * red);
                    }
                }

                int q = (int) Math.round(sum);
                int gray2 = temp | q << 16 | q << 8 | q;

                prosesimage3.setRGB(u, v, gray2);
            }
        }

        lblGambar1.setIcon(new ImageIcon(prosesimage));
        lblGambar2.setIcon(new ImageIcon(prosesimage3));// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        image = new ImageIcon(sumberGambar).getImage();

        size = new Dimension();
        size.width = image.getWidth(null);
        size.height = image.getHeight(null);
        setPreferredSize(size);

        prosesimage3 = new BufferedImage(size.width, size.height, BufferedImage.TYPE_INT_RGB);
        prosesimage = new BufferedImage(size.width, size.height, BufferedImage.TYPE_INT_RGB);

        Graphics g = prosesimage.getGraphics();
        g.drawImage(image, 0, 0, null);

        double filter[][] = {
            {0, -1, 0},
            {-1, 4, -1},
            {0, -1, 0}
        };

        for (int x = 0; x < size.width; x++) {
            for (int y = 0; y < size.height; y++) {

                int RGB = prosesimage.getRGB(x, y);

                int alpha = (RGB << 24) & 0xFF;
                int red = (RGB >> 16) & 0xFF;
                int green = (RGB >> 8) & 0xFF;
                int blue = (RGB >> 0) & 0xFF;

                int avg = (red + green + blue) / 3;
                int gray = alpha | avg << 16 | avg << 8 | avg;

                prosesimage.setRGB(x, y, gray);
            }
        }

        for (int v = 1; v <= size.height - 2; v++) {
            for (int u = 1; u <= size.width - 2; u++) {

                int sum = 0;
                int temp = 0;

                for (int j = -1; j <= 1; j++) {
                    for (int i = -1; i <= 1; i++) {

                        int RGB = prosesimage.getRGB(u + i, v + j);

                        int alpha = (RGB << 24) & 0xFF;
                        int red = (RGB >> 16) & 0xFF;

                        temp = alpha;

                        double c = filter[j + 1][i + 1];
                        sum = (int) (sum + c * red);
                    }
                }

                int q = (int) Math.round(sum);
                int gray2 = temp | q << 16 | q << 8 | q;

                prosesimage3.setRGB(u, v, gray2);
            }
        }

        lblGambar1.setIcon(new ImageIcon(prosesimage));
        lblGambar2.setIcon(new ImageIcon(prosesimage3));// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void noiseuniformActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noiseuniformActionPerformed
    image = new ImageIcon(sumberGambar).getImage();

    size = new Dimension();
    size.width = image.getWidth(null);
    size.height = image.getHeight(null);
    setPreferredSize(size);

    prosesimage = new BufferedImage(
            size.width,
            size.height,
            BufferedImage.TYPE_INT_RGB);

    Graphics g = prosesimage.getGraphics();
    g.drawImage(image, 0, 0, null);

    for (int x = 0; x < size.width; x++) {
        for (int y = 0; y < size.height; y++) {

            int RGB = prosesimage.getRGB(x, y);

            int alpha = (RGB << 24) & 0xFF;
            int red = (RGB >> 16) & 0xFF;
            int green = (RGB >> 8) & 0xFF;
            int blue = RGB & 0xFF;

            int avg = (red + green + blue) / 3;

            double p = Math.random();

            avg = (int)(avg + 256 * p);

            if (avg > 255) {
                avg = 255;
            }

            int gray = alpha | avg << 16 | avg << 8 | avg;

            prosesimage.setRGB(x, y, gray);
        }
    }

    lblGambar2.setIcon(new ImageIcon(prosesimage));

    try {
        ImageIO.write(prosesimage, "png", new File("NoiseUniform.png"));
    } catch (IOException ex) {
        System.err.println(ex);
    }
    }//GEN-LAST:event_noiseuniformActionPerformed

    private void noisesaltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noisesaltActionPerformed
         image = new ImageIcon(sumberGambar).getImage();

    size = new Dimension();
    size.width = image.getWidth(null);
    size.height = image.getHeight(null);
    setPreferredSize(size);

    prosesimage = new BufferedImage(
            size.width,
            size.height,
            BufferedImage.TYPE_INT_RGB);

    Graphics g = prosesimage.getGraphics();
    g.drawImage(image, 0, 0, null);

    for (int x = 0; x < size.width; x++) {
        for (int y = 0; y < size.height; y++) {

            int RGB = prosesimage.getRGB(x, y);

            int alpha = (RGB << 24) & 0xFF;
            int red = (RGB >> 16) & 0xFF;
            int green = (RGB >> 8) & 0xFF;
            int blue = RGB & 0xFF;

            int avg = (red + green + blue) / 3;

            double r = Math.random();
            double p = Double.parseDouble(jTextField4.getText());

            if (r < p) {
                avg = 255;
            }

            int gray = alpha | avg << 16 | avg << 8 | avg;

            prosesimage.setRGB(x, y, gray);
        }
    }

    lblGambar2.setIcon(new ImageIcon(prosesimage));

    try {
        ImageIO.write(prosesimage, "png",
                new File("Noise Salt&pepper.png"));
    } catch (IOException ex) {
        System.err.println(ex);
    }
    }//GEN-LAST:event_noisesaltActionPerformed

    private void noisespeckelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noisespeckelActionPerformed
        image = new ImageIcon(sumberGambar).getImage();

    size = new Dimension();
    size.width = image.getWidth(null);
    size.height = image.getHeight(null);
    setPreferredSize(size);

    prosesimage = new BufferedImage(
            size.width,
            size.height,
            BufferedImage.TYPE_INT_RGB);

    Graphics g = prosesimage.getGraphics();
    g.drawImage(image, 0, 0, null);

    for (int x = 0; x < size.width; x++) {
        for (int y = 0; y < size.height; y++) {

            int RGB = prosesimage.getRGB(x, y);

            int alpha = (RGB << 24) & 0xFF;
            int red = (RGB >> 16) & 0xFF;
            int green = (RGB >> 8) & 0xFF;
            int blue = RGB & 0xFF;

            int avg = (red + green + blue) / 3;

            double r = Math.random();
            double p = Double.parseDouble(jTextField4.getText());

            if (r < p) {
                avg = 0;
            }

            int gray = alpha | avg << 16 | avg << 8 | avg;

            prosesimage.setRGB(x, y, gray);
        }
    }

    lblGambar2.setIcon(new ImageIcon(prosesimage));

    try {
        ImageIO.write(prosesimage, "png",
                new File("Noise Speckle.png"));
    } catch (IOException ex) {
        System.err.println(ex);
    }
    }//GEN-LAST:event_noisespeckelActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
         image = new ImageIcon(sumberGambar).getImage();

    size = new Dimension();
    size.width = image.getWidth(null);
    size.height = image.getHeight(null);
    setPreferredSize(size);

    int Sn = 0;
    int Ss = 0;
    int Sn2 = 0;
    int avg = 0;

    prosesimage = new BufferedImage(
            size.width,
            size.height,
            BufferedImage.TYPE_INT_RGB);

    prosesimage2 = new BufferedImage(
            size.width,
            size.height,
            BufferedImage.TYPE_INT_RGB);

    prosesimage3 = new BufferedImage(
            size.width,
            size.height,
            BufferedImage.TYPE_INT_RGB);

    Graphics g = prosesimage.getGraphics();
    g.drawImage(image, 0, 0, null);

    // Membuat citra noisy
    for (int x = 0; x < size.width; x++) {
        for (int y = 0; y < size.height; y++) {

            int RGB = prosesimage.getRGB(x, y);

            int alpha = (RGB << 24) & 0xFF;
            int red = (RGB >> 16) & 0xFF;
            int green = (RGB >> 8) & 0xFF;
            int blue = RGB & 0xFF;

            avg = (red + green + blue) / 3;

            double r = Math.random();
            double p = Double.parseDouble(jTextField4.getText());

            int avg2 = (int)(avg + r * 256 * p);

            if (avg2 > 255) {
                avg2 = 255;
            }

            int gray =
                    alpha |
                    avg2 << 16 |
                    avg2 << 8 |
                    avg2;

            prosesimage2.setRGB(x, y, gray);

            Sn = Sn + Math.abs(avg2 - avg);
            Ss = Ss + Math.abs(avg);
        }
    }

    // Tampilkan gambar noise
    lblGambar2.setIcon(new ImageIcon(prosesimage2));

    double snr = 10 * Math.log10((double) Ss / Sn);
    jTextField5.setText(Double.toString(snr));

    // Filter rata-rata 5x5
    for (int v = 2; v <= size.height - 3; v++) {
        for (int u = 2; u <= size.width - 3; u++) {

            int sum = 0;
            int temp = 0;

            for (int j = -2; j <= 2; j++) {
                for (int i = -2; i <= 2; i++) {

                    int RGB = prosesimage2.getRGB(u + i, v + j);

                    int alpha = (RGB << 24) & 0xFF;
                    int red = (RGB >> 16) & 0xFF;

                    temp = alpha;
                    sum = sum + red;
                }
            }

            int q = (int)Math.round(sum / 25.0);

            int gray2 =
                    temp |
                    q << 16 |
                    q << 8 |
                    q;

            prosesimage3.setRGB(u, v, gray2);

            Sn2 = Sn2 + Math.abs(q - avg);
        }
    }

    // Tampilkan hasil reduksi noise
    lblGambar3.setIcon(new ImageIcon(prosesimage3));

    double snr2 = 10 * Math.log10((double) Ss / Sn2);
    jTextField6.setText(Double.toString(snr2));   
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        BufferedImage bi = null;

try {

    image = new ImageIcon(sumberGambar).getImage();

    size = new Dimension();
    size.width = image.getWidth(null);
    size.height = image.getHeight(null);

    setPreferredSize(size);

    prosesimage = new BufferedImage(
            size.width,
            size.height,
            BufferedImage.TYPE_INT_RGB);

    prosesimage3 = new BufferedImage(
            size.width,
            size.height,
            BufferedImage.TYPE_INT_RGB);

    Graphics g = prosesimage.getGraphics();
    g.drawImage(image, 0, 0, null);

    lblGambar1.setIcon(new ImageIcon(prosesimage));

    bi = new BufferedImage(
            image.getWidth(null),
            image.getHeight(null),
            BufferedImage.TYPE_BYTE_GRAY);

    Graphics2D g2 = bi.createGraphics();
    g2.drawImage(image, null, null);

    float[] edgeKernel = {
        0, 0, -1, 0, 0,
        0, -1, -2, -1, 0,
        -1, -2, 16, -2, -1,
        0, -1, -2, -1, 0,
        0, 0, -1, 0, 0
    };

    BufferedImageOp edgeOp =
            new ConvolveOp(
                    new Kernel(5, 5, edgeKernel),
                    ConvolveOp.EDGE_NO_OP,
                    null);

    BufferedImage image3 =
            edgeOp.filter(bi, null);

    lblGambar2.setIcon(new ImageIcon(image3));

} catch (Exception e) {
    System.out.println(e);
}
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        BufferedImage bi = null;

try {

    image = new ImageIcon(sumberGambar).getImage();

    size = new Dimension();
    size.width = image.getWidth(null);
    size.height = image.getHeight(null);

    setPreferredSize(size);

    prosesimage3 = new BufferedImage(
            size.width,
            size.height,
            BufferedImage.TYPE_INT_RGB);

    prosesimage = new BufferedImage(
            size.width,
            size.height,
            BufferedImage.TYPE_INT_RGB);

    Graphics g = prosesimage.getGraphics();
    g.drawImage(image, 0, 0, null);

    lblGambar1.setIcon(new ImageIcon(prosesimage));

    bi = new BufferedImage(
            image.getWidth(null),
            image.getHeight(null),
            BufferedImage.TYPE_BYTE_GRAY);

    Graphics2D g2 = bi.createGraphics();
    g2.drawImage(image, null, null);

    float[] edgeKernel = {
        -1, 1
    };

    BufferedImageOp edgeop =
            new ConvolveOp(
                    new Kernel(1, 2, edgeKernel),
                    ConvolveOp.EDGE_NO_OP,
                    null);

    BufferedImage image3 =
            edgeop.filter(bi, null);

    lblGambar2.setIcon(new ImageIcon(image3));

} catch (Exception e) {
    System.out.println(e);
}
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        BufferedImage bi = null;

try {

    image = new ImageIcon(sumberGambar).getImage();

    size = new Dimension();
    size.width = image.getWidth(null);
    size.height = image.getHeight(null);

    setPreferredSize(size);

    prosesimage = new BufferedImage(
            size.width,
            size.height,
            BufferedImage.TYPE_INT_RGB);

    Graphics g = prosesimage.getGraphics();
    g.drawImage(image, 0, 0, null);

    lblGambar1.setIcon(new ImageIcon(prosesimage));

    bi = new BufferedImage(
            image.getWidth(null),
            image.getHeight(null),
            BufferedImage.TYPE_BYTE_GRAY);

    Graphics2D g2 = bi.createGraphics();
    g2.drawImage(image, null, null);

    float[] edgeKernel = {
        -1, 0, 1,
        -1, 0, 1,
        -1, 0, 1
    };

    BufferedImageOp edgeop =
            new ConvolveOp(
                    new Kernel(3, 3, edgeKernel),
                    ConvolveOp.EDGE_NO_OP,
                    null);

    BufferedImage image3 =
            edgeop.filter(bi, null);

    lblGambar2.setIcon(new ImageIcon(image3));

} catch (Exception e) {
    System.out.println(e);
}
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        BufferedImage bi = null;

try {

    image = new ImageIcon(sumberGambar).getImage();

    size = new Dimension();
    size.width = image.getWidth(null);
    size.height = image.getHeight(null);

    setPreferredSize(size);

    prosesimage3 = new BufferedImage(
            size.width,
            size.height,
            BufferedImage.TYPE_INT_RGB);

    prosesimage = new BufferedImage(
            size.width,
            size.height,
            BufferedImage.TYPE_INT_RGB);

    Graphics g = prosesimage.getGraphics();
    g.drawImage(image, 0, 0, null);

    lblGambar1.setIcon(new ImageIcon(prosesimage));

    bi = new BufferedImage(
            image.getWidth(null),
            image.getHeight(null),
            BufferedImage.TYPE_BYTE_GRAY);

    Graphics2D g2 = bi.createGraphics();
    g2.drawImage(image, null, null);

    float[] edgeKernel = {
         0,  1,  0,
         1, -4,  1,
         0,  1,  0
    };

    BufferedImageOp edgeop =
            new ConvolveOp(
                    new Kernel(3, 3, edgeKernel),
                    ConvolveOp.EDGE_NO_OP,
                    null);

    BufferedImage image3 =
            edgeop.filter(bi, null);

    lblGambar2.setIcon(new ImageIcon(image3));

} catch (Exception e) {
    System.out.println(e);
}
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        BufferedImage bi = null;

try {

    image = new ImageIcon(sumberGambar).getImage();

    size = new Dimension();
    size.width = image.getWidth(null);
    size.height = image.getHeight(null);

    setPreferredSize(size);

    prosesimage3 = new BufferedImage(
            size.width,
            size.height,
            BufferedImage.TYPE_INT_RGB);

    prosesimage = new BufferedImage(
            size.width,
            size.height,
            BufferedImage.TYPE_INT_RGB);

    Graphics g = prosesimage.getGraphics();
    g.drawImage(image, 0, 0, null);

    lblGambar1.setIcon(new ImageIcon(prosesimage));

    bi = new BufferedImage(
            image.getWidth(null),
            image.getHeight(null),
            BufferedImage.TYPE_BYTE_GRAY);

    Graphics2D g2 = bi.createGraphics();
    g2.drawImage(image, null, null);

    float[] edgeKernel = {
        -1, -1, -1,
         0,  0,  0,
         1,  1,  1
    };

    BufferedImageOp edgeop =
            new ConvolveOp(
                    new Kernel(3, 3, edgeKernel),
                    ConvolveOp.EDGE_NO_OP,
                    null);

    BufferedImage image3 =
            edgeop.filter(bi, null);

    lblGambar2.setIcon(new ImageIcon(image3));

} catch (Exception e) {
    System.out.println(e);
}
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        BufferedImage bi = null;

try {

    image = new ImageIcon(sumberGambar).getImage();

    size = new Dimension();
    size.width = image.getWidth(null);
    size.height = image.getHeight(null);

    setPreferredSize(size);

    prosesimage3 = new BufferedImage(
            size.width,
            size.height,
            BufferedImage.TYPE_INT_RGB);

    prosesimage = new BufferedImage(
            size.width,
            size.height,
            BufferedImage.TYPE_INT_RGB);

    Graphics g = prosesimage.getGraphics();
    g.drawImage(image, 0, 0, null);

    lblGambar1.setIcon(new ImageIcon(prosesimage));

    bi = new BufferedImage(
            image.getWidth(null),
            image.getHeight(null),
            BufferedImage.TYPE_BYTE_GRAY);

    Graphics2D g2 = bi.createGraphics();
    g2.drawImage(image, null, null);

    float[] edgeKernel = {
        -1, -2, -1,
         0,  0,  0,
         1,  2,  1
    };

    BufferedImageOp edgeop =
            new ConvolveOp(
                    new Kernel(3, 3, edgeKernel),
                    ConvolveOp.EDGE_NO_OP,
                    null);

    BufferedImage image3 =
            edgeop.filter(bi, null);

    lblGambar2.setIcon(new ImageIcon(image3));

} catch (Exception e) {
    System.out.println(e);
}
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        BufferedImage bi = null;

try {

    image = new ImageIcon(sumberGambar).getImage();

    size = new Dimension();
    size.width = image.getWidth(null);
    size.height = image.getHeight(null);

    setPreferredSize(size);

    prosesimage3 = new BufferedImage(
            size.width,
            size.height,
            BufferedImage.TYPE_INT_RGB);

    prosesimage = new BufferedImage(
            size.width,
            size.height,
            BufferedImage.TYPE_INT_RGB);

    Graphics g = prosesimage.getGraphics();
    g.drawImage(image, 0, 0, null);

    lblGambar1.setIcon(new ImageIcon(prosesimage));

    bi = new BufferedImage(
            image.getWidth(null),
            image.getHeight(null),
            BufferedImage.TYPE_BYTE_GRAY);

    Graphics2D g2 = bi.createGraphics();
    g2.drawImage(image, null, null);

    float[] edgeKernel = {
        -1, 0, 1,
        -2, 0, 2,
        -1, 0, 1
    };

    BufferedImageOp edgeop =
            new ConvolveOp(
                    new Kernel(3, 3, edgeKernel),
                    ConvolveOp.EDGE_NO_OP,
                    null);

    BufferedImage image3 =
            edgeop.filter(bi, null);

    lblGambar2.setIcon(new ImageIcon(image3));

} catch (Exception e) {
    System.out.println(e);
}
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        BufferedImage bi = null;

try {

    image = new ImageIcon(sumberGambar).getImage();

    size = new Dimension();
    size.width = image.getWidth(null);
    size.height = image.getHeight(null);

    setPreferredSize(size);

    prosesimage3 = new BufferedImage(
            size.width,
            size.height,
            BufferedImage.TYPE_INT_RGB);

    prosesimage = new BufferedImage(
            size.width,
            size.height,
            BufferedImage.TYPE_INT_RGB);

    Graphics g = prosesimage.getGraphics();
    g.drawImage(image, 0, 0, null);

    lblGambar1.setIcon(new ImageIcon(prosesimage));

    bi = new BufferedImage(
            image.getWidth(null),
            image.getHeight(null),
            BufferedImage.TYPE_BYTE_GRAY);

    Graphics2D g2 = bi.createGraphics();
    g2.drawImage(image, null, null);

    float[] edgeKernel = {
        -1, -1, -1,
        -1,  8, -1,
        -1, -1, -1
    };

    BufferedImageOp edgeop =
            new ConvolveOp(
                    new Kernel(3, 3, edgeKernel),
                    ConvolveOp.EDGE_NO_OP,
                    null);

    BufferedImage image3 =
            edgeop.filter(bi, null);

    lblGambar2.setIcon(new ImageIcon(image3));

} catch (Exception e) {
    System.out.println(e);
}
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPCD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPCD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPCD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPCD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPCD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Deteksitepi;
    private javax.swing.JMenu File;
    private javax.swing.JMenu Noise;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JSlider jSlider2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JLabel lblGambar1;
    private javax.swing.JLabel lblGambar2;
    private javax.swing.JLabel lblGambar3;
    private javax.swing.JMenuItem mnuOpen;
    private javax.swing.JMenuItem mnuOpen2;
    private javax.swing.JMenuItem noisesalt;
    private javax.swing.JMenuItem noisespeckel;
    private javax.swing.JMenuItem noiseuniform;
    // End of variables declaration//GEN-END:variables
}
